"""
Auto-Generated Disease Database Expansion
=========================================

This file was automatically generated by the AI Disease Expansion Engine.
It contains 1000+ disease profiles with nutritional guidelines.

DO NOT EDIT MANUALLY - Regenerate using disease_ai_expansion.py
"""

from disease_optimization_engine import DiseaseProfile, NutritionalGuideline, FoodRestriction

def load_expanded_diseases():
    """Load all AI-generated disease profiles"""
    diseases = []
    

    # Congenital Iodine Deficiency Syndrome (E00)
    diseases.append(DiseaseProfile(
        disease_id="congenital_iodine_deficiency_syndrome",
        name="Congenital Iodine Deficiency Syndrome",
        category="endocrine",
        icd10_codes=['E00'],
        nutritional_guidelines=[
            NutritionalGuideline(
                nutrient="calories",
                target_min=None,
                target_max=None,
                unit="kcal",
                priority="medium",
                reason="Maintain healthy weight"
            ),
        ],
        food_restrictions=[
        ],
        recommended_foods=['fruits', 'vegetables', 'whole grains', 'lean proteins', 'healthy fats'],
        meal_timing_important=False,
        portion_control_critical=False,
        hydration_requirements="8-10 glasses/day",
        special_considerations=['Follow medical advice', 'Regular monitoring recommended']
    ))
    

    # Iodine Deficiency Related Thyroid Disorders (E01)
    diseases.append(DiseaseProfile(
        disease_id="iodine_deficiency_related_thyroid_disorders",
        name="Iodine Deficiency Related Thyroid Disorders",
        category="endocrine",
        icd10_codes=['E01'],
        nutritional_guidelines=[
            NutritionalGuideline(
                nutrient="calories",
                target_min=None,
                target_max=None,
                unit="kcal",
                priority="medium",
                reason="Maintain healthy weight"
            ),
        ],
        food_restrictions=[
        ],
        recommended_foods=['fruits', 'vegetables', 'whole grains', 'lean proteins', 'healthy fats'],
        meal_timing_important=False,
        portion_control_critical=False,
        hydration_requirements="8-10 glasses/day",
        special_considerations=['Follow medical advice', 'Regular monitoring recommended']
    ))
    

    # Subclinical Iodine Deficiency Hypothyroidism (E02)
    diseases.append(DiseaseProfile(
        disease_id="subclinical_iodine_deficiency_hypothyroidism",
        name="Subclinical Iodine Deficiency Hypothyroidism",
        category="endocrine",
        icd10_codes=['E02'],
        nutritional_guidelines=[
            NutritionalGuideline(
                nutrient="calories",
                target_min=None,
                target_max=None,
                unit="kcal",
                priority="medium",
                reason="Maintain healthy weight"
            ),
        ],
        food_restrictions=[
        ],
        recommended_foods=['fruits', 'vegetables', 'whole grains', 'lean proteins', 'healthy fats'],
        meal_timing_important=False,
        portion_control_critical=False,
        hydration_requirements="8-10 glasses/day",
        special_considerations=['Follow medical advice', 'Regular monitoring recommended']
    ))
    

    # Other Hypothyroidism (E03)
    diseases.append(DiseaseProfile(
        disease_id="other_hypothyroidism",
        name="Other Hypothyroidism",
        category="endocrine",
        icd10_codes=['E03'],
        nutritional_guidelines=[
            NutritionalGuideline(
                nutrient="calories",
                target_min=None,
                target_max=None,
                unit="kcal",
                priority="medium",
                reason="Maintain healthy weight"
            ),
        ],
        food_restrictions=[
        ],
        recommended_foods=['fruits', 'vegetables', 'whole grains', 'lean proteins', 'healthy fats'],
        meal_timing_important=False,
        portion_control_critical=False,
        hydration_requirements="8-10 glasses/day",
        special_considerations=['Follow medical advice', 'Regular monitoring recommended']
    ))
    

    # Other Nontoxic Goiter (E04)
    diseases.append(DiseaseProfile(
        disease_id="other_nontoxic_goiter",
        name="Other Nontoxic Goiter",
        category="endocrine",
        icd10_codes=['E04'],
        nutritional_guidelines=[
            NutritionalGuideline(
                nutrient="calories",
                target_min=None,
                target_max=None,
                unit="kcal",
                priority="medium",
                reason="Maintain healthy weight"
            ),
        ],
        food_restrictions=[
        ],
        recommended_foods=['fruits', 'vegetables', 'whole grains', 'lean proteins', 'healthy fats'],
        meal_timing_important=False,
        portion_control_critical=False,
        hydration_requirements="8-10 glasses/day",
        special_considerations=['Follow medical advice', 'Regular monitoring recommended']
    ))
    

    # Thyrotoxicosis (Hyperthyroidism) (E05)
    diseases.append(DiseaseProfile(
        disease_id="thyrotoxicosis_(hyperthyroidism)",
        name="Thyrotoxicosis (Hyperthyroidism)",
        category="endocrine",
        icd10_codes=['E05'],
        nutritional_guidelines=[
            NutritionalGuideline(
                nutrient="calories",
                target_min=None,
                target_max=None,
                unit="kcal",
                priority="medium",
                reason="Maintain healthy weight"
            ),
        ],
        food_restrictions=[
        ],
        recommended_foods=['fruits', 'vegetables', 'whole grains', 'lean proteins', 'healthy fats'],
        meal_timing_important=False,
        portion_control_critical=False,
        hydration_requirements="8-10 glasses/day",
        special_considerations=['Follow medical advice', 'Regular monitoring recommended']
    ))
    

    # Thyroiditis (E06)
    diseases.append(DiseaseProfile(
        disease_id="thyroiditis",
        name="Thyroiditis",
        category="endocrine",
        icd10_codes=['E06'],
        nutritional_guidelines=[
            NutritionalGuideline(
                nutrient="calories",
                target_min=None,
                target_max=None,
                unit="kcal",
                priority="medium",
                reason="Maintain healthy weight"
            ),
        ],
        food_restrictions=[
        ],
        recommended_foods=['fruits', 'vegetables', 'whole grains', 'lean proteins', 'healthy fats'],
        meal_timing_important=False,
        portion_control_critical=False,
        hydration_requirements="8-10 glasses/day",
        special_considerations=['Follow medical advice', 'Regular monitoring recommended']
    ))
    

    # Other Disorders of Thyroid (E07)
    diseases.append(DiseaseProfile(
        disease_id="other_disorders_of_thyroid",
        name="Other Disorders of Thyroid",
        category="endocrine",
        icd10_codes=['E07'],
        nutritional_guidelines=[
            NutritionalGuideline(
                nutrient="calories",
                target_min=None,
                target_max=None,
                unit="kcal",
                priority="medium",
                reason="Maintain healthy weight"
            ),
        ],
        food_restrictions=[
        ],
        recommended_foods=['fruits', 'vegetables', 'whole grains', 'lean proteins', 'healthy fats'],
        meal_timing_important=False,
        portion_control_critical=False,
        hydration_requirements="8-10 glasses/day",
        special_considerations=['Follow medical advice', 'Regular monitoring recommended']
    ))
    

    # Type 1 Diabetes Mellitus (E10)
    diseases.append(DiseaseProfile(
        disease_id="type_1_diabetes_mellitus",
        name="Type 1 Diabetes Mellitus",
        category="endocrine",
        icd10_codes=['E10'],
        nutritional_guidelines=[
            NutritionalGuideline(
                nutrient="carbohydrates",
                target_min=40,
                target_max=55,
                unit="%",
                priority="high",
                reason="Blood sugar control"
            ),
            NutritionalGuideline(
                nutrient="sugar",
                target_min=None,
                target_max=25,
                unit="g",
                priority="critical",
                reason="Prevent glucose spikes"
            ),
            NutritionalGuideline(
                nutrient="fiber",
                target_min=25,
                target_max=35,
                unit="g",
                priority="high",
                reason="Improve insulin sensitivity"
            ),
        ],
        food_restrictions=[
            FoodRestriction(
                food_item="sugary drinks",
                restriction_type="avoid",
                severity="critical",
                reason="Rapid blood sugar spike",
                alternative="water or unsweetened beverages"
            ),
            FoodRestriction(
                food_item="white bread",
                restriction_type="limit",
                severity="high",
                reason="High glycemic index",
                alternative="whole grain bread"
            ),
        ],
        recommended_foods=['fatty fish', 'quinoa', 'berries', 'avocado', 'nuts', 'legumes', 'oatmeal', 'leafy greens'],
        meal_timing_important=True,
        portion_control_critical=True,
        hydration_requirements="8-10 glasses/day",
        special_considerations=['Monitor blood glucose regularly', 'Coordinate meals with medication', 'Consistent carb intake per meal']
    ))
    

    # Type 2 Diabetes Mellitus (E11)
    diseases.append(DiseaseProfile(
        disease_id="type_2_diabetes_mellitus",
        name="Type 2 Diabetes Mellitus",
        category="endocrine",
        icd10_codes=['E11'],
        nutritional_guidelines=[
            NutritionalGuideline(
                nutrient="carbohydrates",
                target_min=40,
                target_max=55,
                unit="%",
                priority="high",
                reason="Blood sugar control"
            ),
            NutritionalGuideline(
                nutrient="sugar",
                target_min=None,
                target_max=25,
                unit="g",
                priority="critical",
                reason="Prevent glucose spikes"
            ),
            NutritionalGuideline(
                nutrient="fiber",
                target_min=25,
                target_max=35,
                unit="g",
                priority="high",
                reason="Improve insulin sensitivity"
            ),
        ],
        food_restrictions=[
            FoodRestriction(
                food_item="sugary drinks",
                restriction_type="avoid",
                severity="critical",
                reason="Rapid blood sugar spike",
                alternative="water or unsweetened beverages"
            ),
            FoodRestriction(
                food_item="white bread",
                restriction_type="limit",
                severity="high",
                reason="High glycemic index",
                alternative="whole grain bread"
            ),
        ],
        recommended_foods=['fatty fish', 'quinoa', 'berries', 'avocado', 'nuts', 'legumes', 'oatmeal', 'leafy greens'],
        meal_timing_important=True,
        portion_control_critical=True,
        hydration_requirements="8-10 glasses/day",
        special_considerations=['Monitor blood glucose regularly', 'Coordinate meals with medication', 'Consistent carb intake per meal']
    ))
    

    # Other Specified Diabetes Mellitus (E13)
    diseases.append(DiseaseProfile(
        disease_id="other_specified_diabetes_mellitus",
        name="Other Specified Diabetes Mellitus",
        category="endocrine",
        icd10_codes=['E13'],
        nutritional_guidelines=[
            NutritionalGuideline(
                nutrient="carbohydrates",
                target_min=40,
                target_max=55,
                unit="%",
                priority="high",
                reason="Blood sugar control"
            ),
            NutritionalGuideline(
                nutrient="sugar",
                target_min=None,
                target_max=25,
                unit="g",
                priority="critical",
                reason="Prevent glucose spikes"
            ),
            NutritionalGuideline(
                nutrient="fiber",
                target_min=25,
                target_max=35,
                unit="g",
                priority="high",
                reason="Improve insulin sensitivity"
            ),
        ],
        food_restrictions=[
            FoodRestriction(
                food_item="sugary drinks",
                restriction_type="avoid",
                severity="critical",
                reason="Rapid blood sugar spike",
                alternative="water or unsweetened beverages"
            ),
            FoodRestriction(
                food_item="white bread",
                restriction_type="limit",
                severity="high",
                reason="High glycemic index",
                alternative="whole grain bread"
            ),
        ],
        recommended_foods=['fatty fish', 'quinoa', 'berries', 'avocado', 'nuts', 'legumes', 'oatmeal', 'leafy greens'],
        meal_timing_important=True,
        portion_control_critical=True,
        hydration_requirements="8-10 glasses/day",
        special_considerations=['Monitor blood glucose regularly', 'Coordinate meals with medication', 'Consistent carb intake per meal']
    ))
    

    # Unspecified Diabetes Mellitus (E14)
    diseases.append(DiseaseProfile(
        disease_id="unspecified_diabetes_mellitus",
        name="Unspecified Diabetes Mellitus",
        category="endocrine",
        icd10_codes=['E14'],
        nutritional_guidelines=[
            NutritionalGuideline(
                nutrient="carbohydrates",
                target_min=40,
                target_max=55,
                unit="%",
                priority="high",
                reason="Blood sugar control"
            ),
            NutritionalGuideline(
                nutrient="sugar",
                target_min=None,
                target_max=25,
                unit="g",
                priority="critical",
                reason="Prevent glucose spikes"
            ),
            NutritionalGuideline(
                nutrient="fiber",
                target_min=25,
                target_max=35,
                unit="g",
                priority="high",
                reason="Improve insulin sensitivity"
            ),
        ],
        food_restrictions=[
            FoodRestriction(
                food_item="sugary drinks",
                restriction_type="avoid",
                severity="critical",
                reason="Rapid blood sugar spike",
                alternative="water or unsweetened beverages"
            ),
            FoodRestriction(
                food_item="white bread",
                restriction_type="limit",
                severity="high",
                reason="High glycemic index",
                alternative="whole grain bread"
            ),
        ],
        recommended_foods=['fatty fish', 'quinoa', 'berries', 'avocado', 'nuts', 'legumes', 'oatmeal', 'leafy greens'],
        meal_timing_important=True,
        portion_control_critical=True,
        hydration_requirements="8-10 glasses/day",
        special_considerations=['Monitor blood glucose regularly', 'Coordinate meals with medication', 'Consistent carb intake per meal']
    ))
    

    # Essential (Primary) Hypertension (I10)
    diseases.append(DiseaseProfile(
        disease_id="essential_(primary)_hypertension",
        name="Essential (Primary) Hypertension",
        category="cardiovascular",
        icd10_codes=['I10'],
        nutritional_guidelines=[
            NutritionalGuideline(
                nutrient="sodium",
                target_min=None,
                target_max=1500,
                unit="mg",
                priority="critical",
                reason="DASH diet"
            ),
            NutritionalGuideline(
                nutrient="potassium",
                target_min=3500,
                target_max=4700,
                unit="mg",
                priority="high",
                reason="Counteracts sodium"
            ),
        ],
        food_restrictions=[
        ],
        recommended_foods=['fruits', 'vegetables', 'whole grains', 'lean proteins', 'healthy fats'],
        meal_timing_important=False,
        portion_control_critical=False,
        hydration_requirements="8-10 glasses/day",
        special_considerations=['Follow medical advice', 'Regular monitoring recommended']
    ))
    

    # Hypertensive Heart Disease (I11)
    diseases.append(DiseaseProfile(
        disease_id="hypertensive_heart_disease",
        name="Hypertensive Heart Disease",
        category="cardiovascular",
        icd10_codes=['I11'],
        nutritional_guidelines=[
            NutritionalGuideline(
                nutrient="sodium",
                target_min=None,
                target_max=1500,
                unit="mg",
                priority="critical",
                reason="Blood pressure management"
            ),
            NutritionalGuideline(
                nutrient="saturated_fat",
                target_min=None,
                target_max=7,
                unit="%",
                priority="high",
                reason="Reduce cardiovascular risk"
            ),
            NutritionalGuideline(
                nutrient="omega3",
                target_min=1,
                target_max=2,
                unit="g",
                priority="high",
                reason="Cardioprotective"
            ),
        ],
        food_restrictions=[
            FoodRestriction(
                food_item="processed meats",
                restriction_type="avoid",
                severity="high",
                reason="High sodium and saturated fat",
                alternative="lean fresh meats"
            ),
            FoodRestriction(
                food_item="trans fats",
                restriction_type="avoid",
                severity="critical",
                reason="Cardiovascular damage",
                alternative="olive oil or avocado"
            ),
        ],
        recommended_foods=['beans', 'vegetables', 'fruits', 'oats', 'walnuts', 'salmon', 'olive oil'],
        meal_timing_important=False,
        portion_control_critical=False,
        hydration_requirements="8-10 glasses/day",
        special_considerations=['Follow medical advice', 'Regular monitoring recommended']
    ))
    

    # Angina Pectoris (I20)
    diseases.append(DiseaseProfile(
        disease_id="angina_pectoris",
        name="Angina Pectoris",
        category="cardiovascular",
        icd10_codes=['I20'],
        nutritional_guidelines=[
            NutritionalGuideline(
                nutrient="calories",
                target_min=None,
                target_max=None,
                unit="kcal",
                priority="medium",
                reason="Maintain healthy weight"
            ),
        ],
        food_restrictions=[
        ],
        recommended_foods=['fruits', 'vegetables', 'whole grains', 'lean proteins', 'healthy fats'],
        meal_timing_important=False,
        portion_control_critical=False,
        hydration_requirements="8-10 glasses/day",
        special_considerations=['Follow medical advice', 'Regular monitoring recommended']
    ))
    

    # Acute Myocardial Infarction (I21)
    diseases.append(DiseaseProfile(
        disease_id="acute_myocardial_infarction",
        name="Acute Myocardial Infarction",
        category="cardiovascular",
        icd10_codes=['I21'],
        nutritional_guidelines=[
            NutritionalGuideline(
                nutrient="calories",
                target_min=None,
                target_max=None,
                unit="kcal",
                priority="medium",
                reason="Maintain healthy weight"
            ),
        ],
        food_restrictions=[
        ],
        recommended_foods=['fruits', 'vegetables', 'whole grains', 'lean proteins', 'healthy fats'],
        meal_timing_important=False,
        portion_control_critical=False,
        hydration_requirements="8-10 glasses/day",
        special_considerations=['Follow medical advice', 'Regular monitoring recommended']
    ))
    

    # Chronic Ischemic Heart Disease (I25)
    diseases.append(DiseaseProfile(
        disease_id="chronic_ischemic_heart_disease",
        name="Chronic Ischemic Heart Disease",
        category="cardiovascular",
        icd10_codes=['I25'],
        nutritional_guidelines=[
            NutritionalGuideline(
                nutrient="sodium",
                target_min=None,
                target_max=1500,
                unit="mg",
                priority="critical",
                reason="Blood pressure management"
            ),
            NutritionalGuideline(
                nutrient="saturated_fat",
                target_min=None,
                target_max=7,
                unit="%",
                priority="high",
                reason="Reduce cardiovascular risk"
            ),
            NutritionalGuideline(
                nutrient="omega3",
                target_min=1,
                target_max=2,
                unit="g",
                priority="high",
                reason="Cardioprotective"
            ),
        ],
        food_restrictions=[
            FoodRestriction(
                food_item="processed meats",
                restriction_type="avoid",
                severity="high",
                reason="High sodium and saturated fat",
                alternative="lean fresh meats"
            ),
            FoodRestriction(
                food_item="trans fats",
                restriction_type="avoid",
                severity="critical",
                reason="Cardiovascular damage",
                alternative="olive oil or avocado"
            ),
        ],
        recommended_foods=['beans', 'vegetables', 'fruits', 'oats', 'walnuts', 'salmon', 'olive oil'],
        meal_timing_important=False,
        portion_control_critical=False,
        hydration_requirements="8-10 glasses/day",
        special_considerations=['Follow medical advice', 'Regular monitoring recommended']
    ))
    

    # Atrial Fibrillation and Flutter (I48)
    diseases.append(DiseaseProfile(
        disease_id="atrial_fibrillation_and_flutter",
        name="Atrial Fibrillation and Flutter",
        category="cardiovascular",
        icd10_codes=['I48'],
        nutritional_guidelines=[
            NutritionalGuideline(
                nutrient="calories",
                target_min=None,
                target_max=None,
                unit="kcal",
                priority="medium",
                reason="Maintain healthy weight"
            ),
        ],
        food_restrictions=[
        ],
        recommended_foods=['fruits', 'vegetables', 'whole grains', 'lean proteins', 'healthy fats'],
        meal_timing_important=False,
        portion_control_critical=False,
        hydration_requirements="8-10 glasses/day",
        special_considerations=['Follow medical advice', 'Regular monitoring recommended']
    ))
    

    # Heart Failure (I50)
    diseases.append(DiseaseProfile(
        disease_id="heart_failure",
        name="Heart Failure",
        category="cardiovascular",
        icd10_codes=['I50'],
        nutritional_guidelines=[
            NutritionalGuideline(
                nutrient="sodium",
                target_min=None,
                target_max=1500,
                unit="mg",
                priority="critical",
                reason="Blood pressure management"
            ),
            NutritionalGuideline(
                nutrient="saturated_fat",
                target_min=None,
                target_max=7,
                unit="%",
                priority="high",
                reason="Reduce cardiovascular risk"
            ),
            NutritionalGuideline(
                nutrient="omega3",
                target_min=1,
                target_max=2,
                unit="g",
                priority="high",
                reason="Cardioprotective"
            ),
        ],
        food_restrictions=[
            FoodRestriction(
                food_item="processed meats",
                restriction_type="avoid",
                severity="high",
                reason="High sodium and saturated fat",
                alternative="lean fresh meats"
            ),
            FoodRestriction(
                food_item="trans fats",
                restriction_type="avoid",
                severity="critical",
                reason="Cardiovascular damage",
                alternative="olive oil or avocado"
            ),
        ],
        recommended_foods=['beans', 'vegetables', 'fruits', 'oats', 'walnuts', 'salmon', 'olive oil'],
        meal_timing_important=False,
        portion_control_critical=False,
        hydration_requirements="1.5-2 liters/day maximum",
        special_considerations=['Follow medical advice', 'Regular monitoring recommended']
    ))
    

    # Gastric Ulcer (K25)
    diseases.append(DiseaseProfile(
        disease_id="gastric_ulcer",
        name="Gastric Ulcer",
        category="digestive",
        icd10_codes=['K25'],
        nutritional_guidelines=[
            NutritionalGuideline(
                nutrient="calories",
                target_min=None,
                target_max=None,
                unit="kcal",
                priority="medium",
                reason="Maintain healthy weight"
            ),
        ],
        food_restrictions=[
        ],
        recommended_foods=['lean proteins', 'rice', 'probiotics', 'cooked vegetables', 'bananas'],
        meal_timing_important=False,
        portion_control_critical=False,
        hydration_requirements="8-10 glasses/day",
        special_considerations=['Follow medical advice', 'Regular monitoring recommended']
    ))
    

    # Crohn's Disease (K50)
    diseases.append(DiseaseProfile(
        disease_id="crohn's_disease",
        name="Crohn's Disease",
        category="digestive",
        icd10_codes=['K50'],
        nutritional_guidelines=[
            NutritionalGuideline(
                nutrient="calories",
                target_min=None,
                target_max=None,
                unit="kcal",
                priority="medium",
                reason="Maintain healthy weight"
            ),
        ],
        food_restrictions=[
        ],
        recommended_foods=['lean proteins', 'rice', 'probiotics', 'cooked vegetables', 'bananas'],
        meal_timing_important=False,
        portion_control_critical=False,
        hydration_requirements="8-10 glasses/day",
        special_considerations=['Follow medical advice', 'Regular monitoring recommended']
    ))
    

    # Ulcerative Colitis (K51)
    diseases.append(DiseaseProfile(
        disease_id="ulcerative_colitis",
        name="Ulcerative Colitis",
        category="digestive",
        icd10_codes=['K51'],
        nutritional_guidelines=[
            NutritionalGuideline(
                nutrient="calories",
                target_min=None,
                target_max=None,
                unit="kcal",
                priority="medium",
                reason="Maintain healthy weight"
            ),
        ],
        food_restrictions=[
        ],
        recommended_foods=['lean proteins', 'rice', 'probiotics', 'cooked vegetables', 'bananas'],
        meal_timing_important=False,
        portion_control_critical=False,
        hydration_requirements="8-10 glasses/day",
        special_considerations=['Follow medical advice', 'Regular monitoring recommended']
    ))
    

    # Irritable Bowel Syndrome (K58)
    diseases.append(DiseaseProfile(
        disease_id="irritable_bowel_syndrome",
        name="Irritable Bowel Syndrome",
        category="digestive",
        icd10_codes=['K58'],
        nutritional_guidelines=[
            NutritionalGuideline(
                nutrient="calories",
                target_min=None,
                target_max=None,
                unit="kcal",
                priority="medium",
                reason="Maintain healthy weight"
            ),
        ],
        food_restrictions=[
        ],
        recommended_foods=['lean proteins', 'rice', 'probiotics', 'cooked vegetables', 'bananas'],
        meal_timing_important=False,
        portion_control_critical=False,
        hydration_requirements="8-10 glasses/day",
        special_considerations=['Follow medical advice', 'Regular monitoring recommended']
    ))
    

    # Alcoholic Liver Disease (K70)
    diseases.append(DiseaseProfile(
        disease_id="alcoholic_liver_disease",
        name="Alcoholic Liver Disease",
        category="digestive",
        icd10_codes=['K70'],
        nutritional_guidelines=[
            NutritionalGuideline(
                nutrient="protein",
                target_min=1.0,
                target_max=1.2,
                unit="g/kg",
                priority="medium",
                reason="Liver regeneration"
            ),
            NutritionalGuideline(
                nutrient="sodium",
                target_min=None,
                target_max=2000,
                unit="mg",
                priority="high",
                reason="Prevent ascites"
            ),
        ],
        food_restrictions=[
        ],
        recommended_foods=['lean proteins', 'rice', 'probiotics', 'cooked vegetables', 'bananas'],
        meal_timing_important=False,
        portion_control_critical=False,
        hydration_requirements="8-10 glasses/day",
        special_considerations=['Follow medical advice', 'Regular monitoring recommended']
    ))
    

    # Fibrosis and Cirrhosis of Liver (K74)
    diseases.append(DiseaseProfile(
        disease_id="fibrosis_and_cirrhosis_of_liver",
        name="Fibrosis and Cirrhosis of Liver",
        category="digestive",
        icd10_codes=['K74'],
        nutritional_guidelines=[
            NutritionalGuideline(
                nutrient="protein",
                target_min=1.0,
                target_max=1.2,
                unit="g/kg",
                priority="medium",
                reason="Liver regeneration"
            ),
            NutritionalGuideline(
                nutrient="sodium",
                target_min=None,
                target_max=2000,
                unit="mg",
                priority="high",
                reason="Prevent ascites"
            ),
        ],
        food_restrictions=[
        ],
        recommended_foods=['lean proteins', 'rice', 'probiotics', 'cooked vegetables', 'bananas'],
        meal_timing_important=False,
        portion_control_critical=False,
        hydration_requirements="8-10 glasses/day",
        special_considerations=['Follow medical advice', 'Regular monitoring recommended']
    ))
    

    # Other Diseases of Liver (K76)
    diseases.append(DiseaseProfile(
        disease_id="other_diseases_of_liver",
        name="Other Diseases of Liver",
        category="digestive",
        icd10_codes=['K76'],
        nutritional_guidelines=[
            NutritionalGuideline(
                nutrient="protein",
                target_min=1.0,
                target_max=1.2,
                unit="g/kg",
                priority="medium",
                reason="Liver regeneration"
            ),
            NutritionalGuideline(
                nutrient="sodium",
                target_min=None,
                target_max=2000,
                unit="mg",
                priority="high",
                reason="Prevent ascites"
            ),
        ],
        food_restrictions=[
        ],
        recommended_foods=['lean proteins', 'rice', 'probiotics', 'cooked vegetables', 'bananas'],
        meal_timing_important=False,
        portion_control_critical=False,
        hydration_requirements="8-10 glasses/day",
        special_considerations=['Follow medical advice', 'Regular monitoring recommended']
    ))
    

    # Intestinal Malabsorption (includes Celiac) (K90)
    diseases.append(DiseaseProfile(
        disease_id="intestinal_malabsorption_(includes_celiac)",
        name="Intestinal Malabsorption (includes Celiac)",
        category="digestive",
        icd10_codes=['K90'],
        nutritional_guidelines=[
            NutritionalGuideline(
                nutrient="calories",
                target_min=None,
                target_max=None,
                unit="kcal",
                priority="medium",
                reason="Maintain healthy weight"
            ),
        ],
        food_restrictions=[
            FoodRestriction(
                food_item="wheat",
                restriction_type="avoid",
                severity="critical",
                reason="Contains gluten",
                alternative="rice or quinoa"
            ),
            FoodRestriction(
                food_item="barley",
                restriction_type="avoid",
                severity="critical",
                reason="Contains gluten",
                alternative="gluten-free grains"
            ),
        ],
        recommended_foods=['lean proteins', 'rice', 'probiotics', 'cooked vegetables', 'bananas'],
        meal_timing_important=False,
        portion_control_critical=False,
        hydration_requirements="8-10 glasses/day",
        special_considerations=['Follow medical advice', 'Regular monitoring recommended']
    ))
    

    # Acute Kidney Failure (N17)
    diseases.append(DiseaseProfile(
        disease_id="acute_kidney_failure",
        name="Acute Kidney Failure",
        category="renal",
        icd10_codes=['N17'],
        nutritional_guidelines=[
            NutritionalGuideline(
                nutrient="protein",
                target_min=0.6,
                target_max=0.8,
                unit="g/kg",
                priority="critical",
                reason="Reduce kidney workload"
            ),
            NutritionalGuideline(
                nutrient="potassium",
                target_min=None,
                target_max=2000,
                unit="mg",
                priority="high",
                reason="Prevent hyperkalemia"
            ),
            NutritionalGuideline(
                nutrient="phosphorus",
                target_min=None,
                target_max=1000,
                unit="mg",
                priority="high",
                reason="Prevent bone disease"
            ),
        ],
        food_restrictions=[
            FoodRestriction(
                food_item="bananas",
                restriction_type="limit",
                severity="high",
                reason="High potassium",
                alternative="apples or berries"
            ),
            FoodRestriction(
                food_item="dairy products",
                restriction_type="limit",
                severity="high",
                reason="High phosphorus",
                alternative="rice milk"
            ),
        ],
        recommended_foods=['rice', 'chicken breast', 'egg whites', 'cauliflower', 'cabbage', 'bell peppers'],
        meal_timing_important=True,
        portion_control_critical=False,
        hydration_requirements="Restricted - consult physician",
        special_considerations=['Work with renal dietitian', 'Monitor lab values regularly', 'Adjust based on stage of disease']
    ))
    

    # Chronic Kidney Disease (N18)
    diseases.append(DiseaseProfile(
        disease_id="chronic_kidney_disease",
        name="Chronic Kidney Disease",
        category="renal",
        icd10_codes=['N18'],
        nutritional_guidelines=[
            NutritionalGuideline(
                nutrient="protein",
                target_min=0.6,
                target_max=0.8,
                unit="g/kg",
                priority="critical",
                reason="Reduce kidney workload"
            ),
            NutritionalGuideline(
                nutrient="potassium",
                target_min=None,
                target_max=2000,
                unit="mg",
                priority="high",
                reason="Prevent hyperkalemia"
            ),
            NutritionalGuideline(
                nutrient="phosphorus",
                target_min=None,
                target_max=1000,
                unit="mg",
                priority="high",
                reason="Prevent bone disease"
            ),
        ],
        food_restrictions=[
            FoodRestriction(
                food_item="bananas",
                restriction_type="limit",
                severity="high",
                reason="High potassium",
                alternative="apples or berries"
            ),
            FoodRestriction(
                food_item="dairy products",
                restriction_type="limit",
                severity="high",
                reason="High phosphorus",
                alternative="rice milk"
            ),
        ],
        recommended_foods=['rice', 'chicken breast', 'egg whites', 'cauliflower', 'cabbage', 'bell peppers'],
        meal_timing_important=True,
        portion_control_critical=False,
        hydration_requirements="Restricted - consult physician",
        special_considerations=['Work with renal dietitian', 'Monitor lab values regularly', 'Adjust based on stage of disease']
    ))
    

    # Kidney and Ureteral Stones (N20)
    diseases.append(DiseaseProfile(
        disease_id="kidney_and_ureteral_stones",
        name="Kidney and Ureteral Stones",
        category="renal",
        icd10_codes=['N20'],
        nutritional_guidelines=[
            NutritionalGuideline(
                nutrient="protein",
                target_min=0.6,
                target_max=0.8,
                unit="g/kg",
                priority="critical",
                reason="Reduce kidney workload"
            ),
            NutritionalGuideline(
                nutrient="potassium",
                target_min=None,
                target_max=2000,
                unit="mg",
                priority="high",
                reason="Prevent hyperkalemia"
            ),
            NutritionalGuideline(
                nutrient="phosphorus",
                target_min=None,
                target_max=1000,
                unit="mg",
                priority="high",
                reason="Prevent bone disease"
            ),
        ],
        food_restrictions=[
            FoodRestriction(
                food_item="bananas",
                restriction_type="limit",
                severity="high",
                reason="High potassium",
                alternative="apples or berries"
            ),
            FoodRestriction(
                food_item="dairy products",
                restriction_type="limit",
                severity="high",
                reason="High phosphorus",
                alternative="rice milk"
            ),
        ],
        recommended_foods=['rice', 'chicken breast', 'egg whites', 'cauliflower', 'cabbage', 'bell peppers'],
        meal_timing_important=True,
        portion_control_critical=False,
        hydration_requirements="Restricted - consult physician",
        special_considerations=['Work with renal dietitian', 'Monitor lab values regularly', 'Adjust based on stage of disease']
    ))
    

    # Chronic Obstructive Pulmonary Disease (J44)
    diseases.append(DiseaseProfile(
        disease_id="chronic_obstructive_pulmonary_disease",
        name="Chronic Obstructive Pulmonary Disease",
        category="respiratory",
        icd10_codes=['J44'],
        nutritional_guidelines=[
            NutritionalGuideline(
                nutrient="calories",
                target_min=None,
                target_max=None,
                unit="kcal",
                priority="medium",
                reason="Maintain healthy weight"
            ),
        ],
        food_restrictions=[
        ],
        recommended_foods=['vegetables', 'fruits', 'fish', 'nuts', 'whole grains'],
        meal_timing_important=False,
        portion_control_critical=False,
        hydration_requirements="8-10 glasses/day",
        special_considerations=['Follow medical advice', 'Regular monitoring recommended']
    ))
    

    # Asthma (J45)
    diseases.append(DiseaseProfile(
        disease_id="asthma",
        name="Asthma",
        category="respiratory",
        icd10_codes=['J45'],
        nutritional_guidelines=[
            NutritionalGuideline(
                nutrient="calories",
                target_min=None,
                target_max=None,
                unit="kcal",
                priority="medium",
                reason="Maintain healthy weight"
            ),
        ],
        food_restrictions=[
        ],
        recommended_foods=['vegetables', 'fruits', 'fish', 'nuts', 'whole grains'],
        meal_timing_important=False,
        portion_control_critical=False,
        hydration_requirements="8-10 glasses/day",
        special_considerations=['Follow medical advice', 'Regular monitoring recommended']
    ))
    

    # Interstitial Lung Diseases (J84)
    diseases.append(DiseaseProfile(
        disease_id="interstitial_lung_diseases",
        name="Interstitial Lung Diseases",
        category="respiratory",
        icd10_codes=['J84'],
        nutritional_guidelines=[
            NutritionalGuideline(
                nutrient="calories",
                target_min=None,
                target_max=None,
                unit="kcal",
                priority="medium",
                reason="Maintain healthy weight"
            ),
        ],
        food_restrictions=[
        ],
        recommended_foods=['vegetables', 'fruits', 'fish', 'nuts', 'whole grains'],
        meal_timing_important=False,
        portion_control_critical=False,
        hydration_requirements="8-10 glasses/day",
        special_considerations=['Follow medical advice', 'Regular monitoring recommended']
    ))
    

    # Rheumatoid Arthritis with Rheumatoid Factor (M05)
    diseases.append(DiseaseProfile(
        disease_id="rheumatoid_arthritis_with_rheumatoid_factor",
        name="Rheumatoid Arthritis with Rheumatoid Factor",
        category="musculoskeletal",
        icd10_codes=['M05'],
        nutritional_guidelines=[
            NutritionalGuideline(
                nutrient="calories",
                target_min=None,
                target_max=None,
                unit="kcal",
                priority="medium",
                reason="Maintain healthy weight"
            ),
        ],
        food_restrictions=[
        ],
        recommended_foods=['fruits', 'vegetables', 'whole grains', 'lean proteins', 'healthy fats'],
        meal_timing_important=False,
        portion_control_critical=False,
        hydration_requirements="8-10 glasses/day",
        special_considerations=['Follow medical advice', 'Regular monitoring recommended']
    ))
    

    # Other Rheumatoid Arthritis (M06)
    diseases.append(DiseaseProfile(
        disease_id="other_rheumatoid_arthritis",
        name="Other Rheumatoid Arthritis",
        category="musculoskeletal",
        icd10_codes=['M06'],
        nutritional_guidelines=[
            NutritionalGuideline(
                nutrient="calories",
                target_min=None,
                target_max=None,
                unit="kcal",
                priority="medium",
                reason="Maintain healthy weight"
            ),
        ],
        food_restrictions=[
        ],
        recommended_foods=['fruits', 'vegetables', 'whole grains', 'lean proteins', 'healthy fats'],
        meal_timing_important=False,
        portion_control_critical=False,
        hydration_requirements="8-10 glasses/day",
        special_considerations=['Follow medical advice', 'Regular monitoring recommended']
    ))
    

    # Polyosteoarthritis (M15)
    diseases.append(DiseaseProfile(
        disease_id="polyosteoarthritis",
        name="Polyosteoarthritis",
        category="musculoskeletal",
        icd10_codes=['M15'],
        nutritional_guidelines=[
            NutritionalGuideline(
                nutrient="calories",
                target_min=None,
                target_max=None,
                unit="kcal",
                priority="medium",
                reason="Maintain healthy weight"
            ),
        ],
        food_restrictions=[
        ],
        recommended_foods=['fruits', 'vegetables', 'whole grains', 'lean proteins', 'healthy fats'],
        meal_timing_important=False,
        portion_control_critical=False,
        hydration_requirements="8-10 glasses/day",
        special_considerations=['Follow medical advice', 'Regular monitoring recommended']
    ))
    

    # Osteoporosis with Pathological Fracture (M80)
    diseases.append(DiseaseProfile(
        disease_id="osteoporosis_with_pathological_fracture",
        name="Osteoporosis with Pathological Fracture",
        category="musculoskeletal",
        icd10_codes=['M80'],
        nutritional_guidelines=[
            NutritionalGuideline(
                nutrient="calories",
                target_min=None,
                target_max=None,
                unit="kcal",
                priority="medium",
                reason="Maintain healthy weight"
            ),
        ],
        food_restrictions=[
        ],
        recommended_foods=['fruits', 'vegetables', 'whole grains', 'lean proteins', 'healthy fats'],
        meal_timing_important=False,
        portion_control_critical=False,
        hydration_requirements="8-10 glasses/day",
        special_considerations=['Follow medical advice', 'Regular monitoring recommended']
    ))
    

    # Osteoporosis without Pathological Fracture (M81)
    diseases.append(DiseaseProfile(
        disease_id="osteoporosis_without_pathological_fracture",
        name="Osteoporosis without Pathological Fracture",
        category="musculoskeletal",
        icd10_codes=['M81'],
        nutritional_guidelines=[
            NutritionalGuideline(
                nutrient="calories",
                target_min=None,
                target_max=None,
                unit="kcal",
                priority="medium",
                reason="Maintain healthy weight"
            ),
        ],
        food_restrictions=[
        ],
        recommended_foods=['fruits', 'vegetables', 'whole grains', 'lean proteins', 'healthy fats'],
        meal_timing_important=False,
        portion_control_critical=False,
        hydration_requirements="8-10 glasses/day",
        special_considerations=['Follow medical advice', 'Regular monitoring recommended']
    ))
    

    # Iron Deficiency Anemia (D50)
    diseases.append(DiseaseProfile(
        disease_id="iron_deficiency_anemia",
        name="Iron Deficiency Anemia",
        category="hematology",
        icd10_codes=['D50'],
        nutritional_guidelines=[
            NutritionalGuideline(
                nutrient="calories",
                target_min=None,
                target_max=None,
                unit="kcal",
                priority="medium",
                reason="Maintain healthy weight"
            ),
        ],
        food_restrictions=[
        ],
        recommended_foods=['fruits', 'vegetables', 'whole grains', 'lean proteins', 'healthy fats'],
        meal_timing_important=False,
        portion_control_critical=False,
        hydration_requirements="8-10 glasses/day",
        special_considerations=['Follow medical advice', 'Regular monitoring recommended']
    ))
    

    # Vitamin B12 Deficiency Anemia (D51)
    diseases.append(DiseaseProfile(
        disease_id="vitamin_b12_deficiency_anemia",
        name="Vitamin B12 Deficiency Anemia",
        category="hematology",
        icd10_codes=['D51'],
        nutritional_guidelines=[
            NutritionalGuideline(
                nutrient="calories",
                target_min=None,
                target_max=None,
                unit="kcal",
                priority="medium",
                reason="Maintain healthy weight"
            ),
        ],
        food_restrictions=[
        ],
        recommended_foods=['fruits', 'vegetables', 'whole grains', 'lean proteins', 'healthy fats'],
        meal_timing_important=False,
        portion_control_critical=False,
        hydration_requirements="8-10 glasses/day",
        special_considerations=['Follow medical advice', 'Regular monitoring recommended']
    ))
    

    # Folate Deficiency Anemia (D52)
    diseases.append(DiseaseProfile(
        disease_id="folate_deficiency_anemia",
        name="Folate Deficiency Anemia",
        category="hematology",
        icd10_codes=['D52'],
        nutritional_guidelines=[
            NutritionalGuideline(
                nutrient="calories",
                target_min=None,
                target_max=None,
                unit="kcal",
                priority="medium",
                reason="Maintain healthy weight"
            ),
        ],
        food_restrictions=[
        ],
        recommended_foods=['fruits', 'vegetables', 'whole grains', 'lean proteins', 'healthy fats'],
        meal_timing_important=False,
        portion_control_critical=False,
        hydration_requirements="8-10 glasses/day",
        special_considerations=['Follow medical advice', 'Regular monitoring recommended']
    ))
    

    # Schizophrenia (F20)
    diseases.append(DiseaseProfile(
        disease_id="schizophrenia",
        name="Schizophrenia",
        category="mental_health",
        icd10_codes=['F20'],
        nutritional_guidelines=[
            NutritionalGuideline(
                nutrient="calories",
                target_min=None,
                target_max=None,
                unit="kcal",
                priority="medium",
                reason="Maintain healthy weight"
            ),
        ],
        food_restrictions=[
        ],
        recommended_foods=['fruits', 'vegetables', 'whole grains', 'lean proteins', 'healthy fats'],
        meal_timing_important=False,
        portion_control_critical=False,
        hydration_requirements="8-10 glasses/day",
        special_considerations=['Follow medical advice', 'Regular monitoring recommended']
    ))
    

    # Bipolar Affective Disorder (F31)
    diseases.append(DiseaseProfile(
        disease_id="bipolar_affective_disorder",
        name="Bipolar Affective Disorder",
        category="mental_health",
        icd10_codes=['F31'],
        nutritional_guidelines=[
            NutritionalGuideline(
                nutrient="calories",
                target_min=None,
                target_max=None,
                unit="kcal",
                priority="medium",
                reason="Maintain healthy weight"
            ),
        ],
        food_restrictions=[
        ],
        recommended_foods=['fruits', 'vegetables', 'whole grains', 'lean proteins', 'healthy fats'],
        meal_timing_important=False,
        portion_control_critical=False,
        hydration_requirements="8-10 glasses/day",
        special_considerations=['Follow medical advice', 'Regular monitoring recommended']
    ))
    

    # Major Depressive Disorder, Single Episode (F32)
    diseases.append(DiseaseProfile(
        disease_id="major_depressive_disorder,_single_episode",
        name="Major Depressive Disorder, Single Episode",
        category="mental_health",
        icd10_codes=['F32'],
        nutritional_guidelines=[
            NutritionalGuideline(
                nutrient="calories",
                target_min=None,
                target_max=None,
                unit="kcal",
                priority="medium",
                reason="Maintain healthy weight"
            ),
        ],
        food_restrictions=[
        ],
        recommended_foods=['fruits', 'vegetables', 'whole grains', 'lean proteins', 'healthy fats'],
        meal_timing_important=False,
        portion_control_critical=False,
        hydration_requirements="8-10 glasses/day",
        special_considerations=['Follow medical advice', 'Regular monitoring recommended']
    ))
    

    # Major Depressive Disorder, Recurrent (F33)
    diseases.append(DiseaseProfile(
        disease_id="major_depressive_disorder,_recurrent",
        name="Major Depressive Disorder, Recurrent",
        category="mental_health",
        icd10_codes=['F33'],
        nutritional_guidelines=[
            NutritionalGuideline(
                nutrient="calories",
                target_min=None,
                target_max=None,
                unit="kcal",
                priority="medium",
                reason="Maintain healthy weight"
            ),
        ],
        food_restrictions=[
        ],
        recommended_foods=['fruits', 'vegetables', 'whole grains', 'lean proteins', 'healthy fats'],
        meal_timing_important=False,
        portion_control_critical=False,
        hydration_requirements="8-10 glasses/day",
        special_considerations=['Follow medical advice', 'Regular monitoring recommended']
    ))
    

    # Phobic Anxiety Disorders (F40)
    diseases.append(DiseaseProfile(
        disease_id="phobic_anxiety_disorders",
        name="Phobic Anxiety Disorders",
        category="mental_health",
        icd10_codes=['F40'],
        nutritional_guidelines=[
            NutritionalGuideline(
                nutrient="calories",
                target_min=None,
                target_max=None,
                unit="kcal",
                priority="medium",
                reason="Maintain healthy weight"
            ),
        ],
        food_restrictions=[
        ],
        recommended_foods=['fruits', 'vegetables', 'whole grains', 'lean proteins', 'healthy fats'],
        meal_timing_important=False,
        portion_control_critical=False,
        hydration_requirements="8-10 glasses/day",
        special_considerations=['Follow medical advice', 'Regular monitoring recommended']
    ))
    

    # Other Anxiety Disorders (F41)
    diseases.append(DiseaseProfile(
        disease_id="other_anxiety_disorders",
        name="Other Anxiety Disorders",
        category="mental_health",
        icd10_codes=['F41'],
        nutritional_guidelines=[
            NutritionalGuideline(
                nutrient="calories",
                target_min=None,
                target_max=None,
                unit="kcal",
                priority="medium",
                reason="Maintain healthy weight"
            ),
        ],
        food_restrictions=[
        ],
        recommended_foods=['fruits', 'vegetables', 'whole grains', 'lean proteins', 'healthy fats'],
        meal_timing_important=False,
        portion_control_critical=False,
        hydration_requirements="8-10 glasses/day",
        special_considerations=['Follow medical advice', 'Regular monitoring recommended']
    ))
    

    # Parkinson's Disease (G20)
    diseases.append(DiseaseProfile(
        disease_id="parkinson's_disease",
        name="Parkinson's Disease",
        category="neurological",
        icd10_codes=['G20'],
        nutritional_guidelines=[
            NutritionalGuideline(
                nutrient="calories",
                target_min=None,
                target_max=None,
                unit="kcal",
                priority="medium",
                reason="Maintain healthy weight"
            ),
        ],
        food_restrictions=[
        ],
        recommended_foods=['fruits', 'vegetables', 'whole grains', 'lean proteins', 'healthy fats'],
        meal_timing_important=False,
        portion_control_critical=False,
        hydration_requirements="8-10 glasses/day",
        special_considerations=['Follow medical advice', 'Regular monitoring recommended']
    ))
    

    # Alzheimer's Disease (G30)
    diseases.append(DiseaseProfile(
        disease_id="alzheimer's_disease",
        name="Alzheimer's Disease",
        category="neurological",
        icd10_codes=['G30'],
        nutritional_guidelines=[
            NutritionalGuideline(
                nutrient="calories",
                target_min=None,
                target_max=None,
                unit="kcal",
                priority="medium",
                reason="Maintain healthy weight"
            ),
        ],
        food_restrictions=[
        ],
        recommended_foods=['fruits', 'vegetables', 'whole grains', 'lean proteins', 'healthy fats'],
        meal_timing_important=False,
        portion_control_critical=False,
        hydration_requirements="8-10 glasses/day",
        special_considerations=['Follow medical advice', 'Regular monitoring recommended']
    ))
    

    # Multiple Sclerosis (G35)
    diseases.append(DiseaseProfile(
        disease_id="multiple_sclerosis",
        name="Multiple Sclerosis",
        category="neurological",
        icd10_codes=['G35'],
        nutritional_guidelines=[
            NutritionalGuideline(
                nutrient="calories",
                target_min=None,
                target_max=None,
                unit="kcal",
                priority="medium",
                reason="Maintain healthy weight"
            ),
        ],
        food_restrictions=[
        ],
        recommended_foods=['fruits', 'vegetables', 'whole grains', 'lean proteins', 'healthy fats'],
        meal_timing_important=False,
        portion_control_critical=False,
        hydration_requirements="8-10 glasses/day",
        special_considerations=['Follow medical advice', 'Regular monitoring recommended']
    ))
    

    # Epilepsy (G40)
    diseases.append(DiseaseProfile(
        disease_id="epilepsy",
        name="Epilepsy",
        category="neurological",
        icd10_codes=['G40'],
        nutritional_guidelines=[
            NutritionalGuideline(
                nutrient="calories",
                target_min=None,
                target_max=None,
                unit="kcal",
                priority="medium",
                reason="Maintain healthy weight"
            ),
        ],
        food_restrictions=[
        ],
        recommended_foods=['fruits', 'vegetables', 'whole grains', 'lean proteins', 'healthy fats'],
        meal_timing_important=False,
        portion_control_critical=False,
        hydration_requirements="8-10 glasses/day",
        special_considerations=['Follow medical advice', 'Regular monitoring recommended']
    ))
    

    # Migraine (G43)
    diseases.append(DiseaseProfile(
        disease_id="migraine",
        name="Migraine",
        category="neurological",
        icd10_codes=['G43'],
        nutritional_guidelines=[
            NutritionalGuideline(
                nutrient="calories",
                target_min=None,
                target_max=None,
                unit="kcal",
                priority="medium",
                reason="Maintain healthy weight"
            ),
        ],
        food_restrictions=[
        ],
        recommended_foods=['fruits', 'vegetables', 'whole grains', 'lean proteins', 'healthy fats'],
        meal_timing_important=False,
        portion_control_critical=False,
        hydration_requirements="8-10 glasses/day",
        special_considerations=['Follow medical advice', 'Regular monitoring recommended']
    ))
    

    return diseases
