"""
LLM-Powered Disease API
========================

Flask API that serves disease profiles generated by LLM with caching
"""

from flask import Flask, request, jsonify
from flask_cors import CORS
from llm_hybrid_disease_db import LLMHybridDiseaseDatabase
from disease_optimization_engine import MultiDiseaseOptimizer
import os

app = Flask(__name__)
CORS(app)

# Initialize hybrid database
db = LLMHybridDiseaseDatabase(
    cache_dir="./disease_profiles_cache",
    use_llm=True,  # Set to False to disable LLM and use only hardcoded data
    cache_ttl_days=30
)

# Initialize optimizer
optimizer = MultiDiseaseOptimizer(db.fallback_db)  # Uses fallback DB for now


@app.route('/health', methods=['GET'])
def health_check():
    """Health check endpoint"""
    llm_status = "enabled" if db.use_llm and db.llm_generator and db.llm_generator.client else "disabled"
    
    return jsonify({
        "status": "healthy",
        "llm_mode": llm_status,
        "cache_dir": db.cache_dir,
        "cache_ttl_days": db.cache_ttl_days,
        "total_diseases": len(db.get_all_diseases())
    })


@app.route('/api/v1/disease/<disease_id>', methods=['GET'])
def get_disease(disease_id):
    """
    Get disease profile
    
    Query params:
        force_regenerate: bool - Force LLM regeneration even if cached
    """
    force_regenerate = request.args.get('force_regenerate', 'false').lower() == 'true'
    
    disease = db.get_disease(disease_id, force_regenerate=force_regenerate)
    
    if not disease:
        return jsonify({"error": f"Disease not found: {disease_id}"}), 404
    
    return jsonify({
        "disease_id": disease.disease_id,
        "name": disease.name,
        "icd10_codes": disease.icd10_codes,
        "category": disease.category,
        "nutritional_guidelines": [
            {
                "nutrient": g.nutrient,
                "target": g.target,
                "unit": g.unit,
                "priority": g.priority,
                "reasoning": getattr(g, 'reasoning', '')
            }
            for g in disease.nutritional_guidelines
        ],
        "food_restrictions": [
            {
                "food_item": r.food_item,
                "severity": r.severity,
                "reason": r.reason,
                "alternative": r.alternative
            }
            for r in disease.food_restrictions
        ],
        "recommended_foods": disease.recommended_foods,
        "meal_timing": disease.meal_timing,
        "portion_control": disease.portion_control
    })


@app.route('/api/v1/diseases', methods=['GET'])
def list_diseases():
    """
    List all available diseases
    
    Query params:
        category: str - Filter by category
    """
    category = request.args.get('category')
    
    all_diseases = db.get_all_diseases()
    
    if category:
        all_diseases = {
            did: d for did, d in all_diseases.items() 
            if d.category == category
        }
    
    return jsonify({
        "total": len(all_diseases),
        "diseases": [
            {
                "disease_id": did,
                "name": d.name,
                "icd10_codes": d.icd10_codes,
                "category": d.category
            }
            for did, d in all_diseases.items()
        ]
    })


@app.route('/api/v1/categories', methods=['GET'])
def list_categories():
    """List all disease categories"""
    all_diseases = db.get_all_diseases()
    
    categories = {}
    for did, disease in all_diseases.items():
        if disease.category not in categories:
            categories[disease.category] = 0
        categories[disease.category] += 1
    
    return jsonify({
        "total_categories": len(categories),
        "categories": [
            {"name": cat, "count": count}
            for cat, count in sorted(categories.items())
        ]
    })


@app.route('/api/v1/optimize', methods=['POST'])
def optimize_nutrition():
    """
    Optimize nutrition for family with multiple diseases
    
    Request body:
    {
        "family_members": [
            {
                "name": "John",
                "age": 55,
                "diseases": ["diabetes_type2", "hypertension"],
                "dietary_preference": "non-vegetarian"
            }
        ]
    }
    """
    data = request.json
    family_members = data.get('family_members', [])
    
    if not family_members:
        return jsonify({"error": "family_members required"}), 400
    
    try:
        result = optimizer.optimize_for_family(family_members)
        return jsonify(result)
    except Exception as e:
        return jsonify({"error": str(e)}), 500


@app.route('/api/v1/llm/generate', methods=['POST'])
def generate_llm_profile():
    """
    Generate new disease profile using LLM
    
    Request body:
    {
        "disease_name": "Type 2 Diabetes Mellitus",
        "icd10_code": "E11",
        "category": "endocrine",
        "patient_context": {
            "age": 55,
            "severity": "moderate"
        }
    }
    """
    if not db.use_llm or not db.llm_generator or not db.llm_generator.client:
        return jsonify({"error": "LLM not configured"}), 503
    
    data = request.json
    disease_name = data.get('disease_name')
    
    if not disease_name:
        return jsonify({"error": "disease_name required"}), 400
    
    llm_profile = db.llm_generator.generate_disease_profile(
        disease_name=disease_name,
        icd10_code=data.get('icd10_code'),
        category=data.get('category'),
        patient_context=data.get('patient_context')
    )
    
    if not llm_profile:
        return jsonify({"error": "Failed to generate profile"}), 500
    
    return jsonify({
        "disease_id": llm_profile.disease_id,
        "name": llm_profile.name,
        "icd10_codes": llm_profile.icd10_codes,
        "category": llm_profile.category,
        "nutritional_guidelines": [
            {
                "nutrient": g.nutrient,
                "target": g.target,
                "unit": g.unit,
                "priority": g.priority,
                "reasoning": g.reasoning
            }
            for g in llm_profile.nutritional_guidelines
        ],
        "food_restrictions": [
            {
                "food_item": r.food_item,
                "severity": r.severity,
                "reason": r.reason,
                "alternatives": r.alternatives
            }
            for r in llm_profile.food_restrictions
        ],
        "recommended_foods": llm_profile.recommended_foods,
        "meal_timing": llm_profile.meal_timing,
        "portion_control": llm_profile.portion_control,
        "evidence_sources": llm_profile.evidence_sources,
        "llm_model": llm_profile.llm_model,
        "last_updated": llm_profile.last_updated
    })


@app.route('/api/v1/llm/batch-generate', methods=['POST'])
def batch_generate_profiles():
    """
    Batch generate profiles for multiple diseases
    
    Request body:
    {
        "diseases": [
            {"name": "Type 2 Diabetes", "icd10": "E11", "category": "endocrine"}
        ],
        "delay": 2.0
    }
    """
    if not db.use_llm or not db.llm_generator or not db.llm_generator.client:
        return jsonify({"error": "LLM not configured"}), 503
    
    data = request.json
    diseases = data.get('diseases', [])
    delay = data.get('delay', 2.0)
    
    if not diseases:
        return jsonify({"error": "diseases list required"}), 400
    
    # Estimate cost
    estimated_cost_min = len(diseases) * 0.1
    estimated_cost_max = len(diseases) * 0.5
    
    profiles = db.llm_generator.batch_generate_profiles(
        diseases=diseases,
        delay=delay,
        cache_dir=db.cache_dir
    )
    
    return jsonify({
        "generated": len(profiles),
        "total_diseases": len(diseases),
        "tokens_used": db.llm_generator.total_tokens,
        "estimated_cost": f"${estimated_cost_min:.2f} - ${estimated_cost_max:.2f}",
        "profiles": list(profiles.keys())
    })


@app.route('/api/v1/cache/stats', methods=['GET'])
def cache_stats():
    """Get cache statistics"""
    stats = db.get_cache_stats()
    return jsonify(stats)


@app.route('/api/v1/cache/clear', methods=['POST'])
def clear_cache():
    """
    Clear cache
    
    Request body (optional):
    {
        "disease_id": "diabetes_type2"
    }
    """
    data = request.json or {}
    disease_id = data.get('disease_id')
    
    db.clear_cache(disease_id)
    
    return jsonify({
        "message": f"Cache cleared for {disease_id}" if disease_id else "All cache cleared"
    })


@app.route('/api/v1/llm/config', methods=['GET'])
def get_llm_config():
    """Get LLM configuration"""
    if not db.llm_generator:
        return jsonify({"enabled": False})
    
    return jsonify({
        "enabled": db.use_llm,
        "client_initialized": db.llm_generator.client is not None,
        "provider": db.llm_generator.provider,
        "model": db.llm_generator.model,
        "total_tokens_used": db.llm_generator.total_tokens
    })


@app.route('/api/v1/llm/config', methods=['POST'])
def update_llm_config():
    """
    Update LLM configuration
    
    Request body:
    {
        "api_key": "sk-...",
        "provider": "openai",
        "model": "gpt-4-turbo-preview"
    }
    """
    data = request.json
    
    api_key = data.get('api_key')
    provider = data.get('provider', 'openai')
    model = data.get('model', 'gpt-4-turbo-preview')
    
    # Reinitialize generator
    db.llm_generator = LLMDiseaseProfileGenerator(
        api_key=api_key,
        provider=provider,
        model=model
    )
    
    return jsonify({
        "message": "LLM configuration updated",
        "provider": provider,
        "model": model,
        "client_initialized": db.llm_generator.client is not None
    })


@app.route('/', methods=['GET'])
def index():
    """API documentation"""
    return jsonify({
        "name": "LLM-Powered Disease Nutrition API",
        "version": "1.0.0",
        "description": "Disease nutritional profiles with LLM generation and caching",
        "endpoints": {
            "GET /health": "Health check",
            "GET /api/v1/disease/<id>": "Get disease profile (with optional LLM generation)",
            "GET /api/v1/diseases": "List all diseases",
            "GET /api/v1/categories": "List disease categories",
            "POST /api/v1/optimize": "Optimize nutrition for family",
            "POST /api/v1/llm/generate": "Generate new LLM profile",
            "POST /api/v1/llm/batch-generate": "Batch generate profiles",
            "GET /api/v1/cache/stats": "Get cache statistics",
            "POST /api/v1/cache/clear": "Clear cache",
            "GET /api/v1/llm/config": "Get LLM configuration",
            "POST /api/v1/llm/config": "Update LLM configuration"
        },
        "llm_status": "enabled" if db.use_llm and db.llm_generator and db.llm_generator.client else "disabled"
    })


if __name__ == '__main__':
    print("\n" + "="*80)
    print("LLM-POWERED DISEASE NUTRITION API")
    print("="*80)
    print(f"\nLLM Mode: {'Enabled' if db.use_llm and db.llm_generator and db.llm_generator.client else 'Disabled'}")
    print(f"Total Diseases: {len(db.get_all_diseases())}")
    print(f"Cache Directory: {db.cache_dir}")
    
    if not db.llm_generator or not db.llm_generator.client:
        print("\n⚠️ LLM NOT CONFIGURED")
        print("To enable LLM features:")
        print("  1. pip install openai")
        print("  2. Set OPENAI_API_KEY environment variable")
        print("\nAPI will use fallback database until LLM is configured.")
    else:
        print("\n✅ LLM READY")
        print(f"Provider: {db.llm_generator.provider}")
        print(f"Model: {db.llm_generator.model}")
    
    print("\n" + "="*80)
    print("Starting API server on http://127.0.0.1:5003")
    print("="*80 + "\n")
    
    app.run(host='127.0.0.1', port=5003, debug=True)
